version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongo-livro
    restart: always
    ports:
      - "27277:27017"            # Porta do Mongo
    volumes:
      - mongo-data:/data/db                      # Volume persistente para os dados
      - ./init:/docker-entrypoint-initdb.d       # Volume para inserir os primeiros dados
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
      MONGO_INITDB_DATABASE: livraria

  # Instala e configura o mongo-express
  mongo-express:
    image: mongo-express
    container_name: mongo-express-livro
    restart: always
    ports:
      - "8881:8081"              # Acesso via navegador
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin      # dados do mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha123   # dados do mongodb
      ME_CONFIG_MONGODB_SERVER: mongodb           # dados do mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin         # dados do mongo-express
      ME_CONFIG_BASICAUTH_PASSWORD: senha123      # dados do mongo-express
    depends_on:
      - mongodb

volumes:
  mongo-data: