version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongo-livro
    restart: always
    ports:
      - "27277:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
      MONGO_INITDB_DATABASE: livraria
    volumes:
      - mongo-data:/data/db
      - ./init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    container_name: mongo-express-livro
    restart: always
    ports:
      - "8881:8081"              # Acesso via navegador
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin      # dados do mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha123   # dados do mongodb
      ME_CONFIG_MONGODB_SERVER: mongodb           # dados do mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin         # dados do mongo-express
      ME_CONFIG_BASICAUTH_PASSWORD: senha123      # dados do mongo-express
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: node-livro-backend
    container_name: backend-livro
    ports:
      - "3332:3000"
    environment:
      MONGO_URI: mongodb://admin:senha123@mongodb:27017/livraria?authSource=admin        # como o mongodb está como container, deve ser usada a porta interna, ou seja, 27017
    volumes:
      - ./backend:/app                      
    depends_on:
      - mongodb
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node-livro-frontend
    container_name: frontend-livro
    ports:
      - "3331:3000"
    volumes:
      - ./frontend:/app                     
    depends_on:
      - backend
    command: npm run dev

volumes:
  mongo-data: